# nginx 공통 설정
events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    # 정적 파일 전송 최적화 옵션
    sendfile on;
    # 서버와 클라이언트 연결 시간
    keepalive_timeout 65;
    # 서버 정보 숨김
    server_tokens off;

    include /etc/nginx/conf.d/*.conf;
}