FROM nginx:alpine

COPY ./deploy/common/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./deploy/web/conf.d/web.conf /etc/nginx/conf.d/web.conf
COPY ./deploy/web/conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY ./deploy/web/html/ /usr/share/nginx/html/

EXPOSE 80

CMD [ "sh", "-c", "exit 1" ]