FROM nginx:alpine

COPY ./deploy/nginx_conf/nginx.conf /etc/nginx/nginx.conf
COPY ./deploy/conf.d/web.conf /etc/nginx/conf.d/web.conf
COPY ./deploy/conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY ./deploy/html/web/ /usr/share/nginx/html/

EXPOSE 80