FROM nginx:alpine

COPY ./deploy/nginx_conf/nginx.conf /etc/nginx/nginx.conf
COPY ./deploy/conf.d/admin.conf /etc/nginx/conf.d/admin.conf
COPY ./deploy/conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY ./deploy/html/admin/ /usr/share/nginx/html/

EXPOSE 80