server {
    listen 80 default_server;
    server_name _;

    location = /health {
        access_log off;
        default_type text/plain;
        return 500 'fail';
    }

    location / {
        return 404;
    }
}

# server {
#     listen 80 default_server;
#     server_name _;

#     location  = /health {
#         access_log off;
#         default_type text/plain;
#         return 200 'ok';
#     }

#     location / {
#         return 404;
#     }
# }