# 잘못된 요청 처리
server {
    listen 80 default_server;
    server_name _;

    location  = /health {
        access_log off;
        default_type text/plain;
        return 200 'ok';
    }

    location / {
        return 404;
    }
}